git config --global alias.cm "commit"
git config --global alias.s "status"
git config --global alias.l "log --oneline --graph"
git config --global alias.a "add"
git config --global alias.alias "config --get-regex ^alias"